export const SUBJECT = [
{ name: 'Mathematics',  value: 'Mathematics' },
{ name: 'General Sciences',  value: 'General Sciences'},
{ name: 'Physics',  value: 'Physics'},
{ name: 'Chemistry',  value: 'Chemistry'},
{ name: 'Biology',  value: 'Biology'},
{ name: 'Geography',  value: 'Geography'},
{ name: 'History',  value: 'History'},
{ name: 'Religion',  value: 'Religion'},
{ name: 'Politics',  value: 'Politics'},
{ name: 'Sport',  value: 'Sport'},
{ name: 'Music',  value: 'Music'},
{ name: 'Art',  value: 'Art'},
{ name: 'Art History',  value: 'Art History'},
{ name: 'Economics',  value: 'Economics'},
{ name: 'Business Studies',  value: 'Business Studies'},
{ name: 'Accounting',  value: 'Accounting'},
{ name: 'Computing',  value: 'Computing'},
{ name: 'Life and career orientation',  value: 'Life and career orientation'},
{ name: 'Law',  value: 'Law'},
{ name: 'Philosophy',  value: 'Philosophy'},
{ name: 'Theater',  value: 'Theater'},
{ name: 'Psychology',  value: 'Psychology'}
];