export const SUBJECT = [
  { name: 'Mathematics', value: 'math' },
  { name: 'General Sciences', value: 'science' },
  { name: 'Physics', value: 'physics' },
  { name: 'Chemistry', value: 'chemistry' },
  { name: 'Biology', value: 'biology' },
  { name: 'Geography', value: 'geography' },
  { name: 'History', value: 'history' },
  { name: 'Religion', value: 'religion' },
  { name: 'Politics', value: 'politics' },
  { name: 'Sport', value: 'sport' },
  { name: 'Music', value: 'music' },
  { name: 'Art', value: 'art' },
  { name: 'Art history', value: 'art_history' },
  { name: 'Economics', value: 'economics' },
  { name: 'Business Studies', value: 'business' },
  { name: 'Accounting', value: 'accounting' },
  { name: 'Computing', value: 'computing' },
  { name: 'Life and career orientation', value: 'life' },
  { name: 'Law', value: 'law' },
  { name: 'Phylosophy', value: 'phylosophy' },
  { name: 'Theater', value: 'theater' },
  { name: 'Psychology', value: 'psychology' },
  { name: 'Language class', value: 'language' },
];
