/**
 * globy-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body6 { 
    name?: string;
    language?: string;
    subject?: string;
    country?: string;
    projectDuration?: number;
    meetingFrequency?: number;
    level?: number;
    languageLevel?: string;
    topics?: Array<string>;
}