/**
 * globy-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassesclassIdprojectsprojectIdmeetingsTaskListSimpleTasks } from './classesclassIdprojectsprojectIdmeetingsTaskListSimpleTasks';

export interface ClassesclassIdprojectsprojectIdmeetingsTaskList { 
    quizzes?: Array<any>;
    aliases?: Array<any>;
    drawits?: Array<any>;
    simpleTasks?: Array<ClassesclassIdprojectsprojectIdmeetingsTaskListSimpleTasks>;
}