/**
 * globy-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassesTeacher } from './classesTeacher';
import { ClassesclassIdprojectsClasses } from './classesclassIdprojectsClasses';

export interface InlineResponse20010 { 
    id?: string;
    classes?: Array<ClassesclassIdprojectsClasses>;
    state?: InlineResponse20010.StateEnum;
    messages?: Array<Array<any>>;
    meetings?: Array<any>;
    startedBy?: ClassesTeacher;
}
export namespace InlineResponse20010 {
    export type StateEnum = 'pending' | 'ongoing' | 'done';
    export const StateEnum = {
        Pending: 'pending' as StateEnum,
        Ongoing: 'ongoing' as StateEnum,
        Done: 'done' as StateEnum
    };
}