/**
 * globy-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse2004 { 
    id?: string;
    email?: string;
    firstName?: string;
    role?: InlineResponse2004.RoleEnum;
}
export namespace InlineResponse2004 {
    export type RoleEnum = 'teacher' | 'student';
    export const RoleEnum = {
        Teacher: 'teacher' as RoleEnum,
        Student: 'student' as RoleEnum
    };
}