/**
 * globy-backend
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClassesTeacher } from './classesTeacher';
import { MenotificationsCta } from './menotificationsCta';

export interface Notification { 
    id?: string;
    title?: string;
    text?: string;
    opened?: boolean;
    type?: Notification.TypeEnum;
    cta?: MenotificationsCta;
    user?: ClassesTeacher;
}
export namespace Notification {
    export type TypeEnum = 'notification' | 'email' | 'all';
    export const TypeEnum = {
        Notification: 'notification' as TypeEnum,
        Email: 'email' as TypeEnum,
        All: 'all' as TypeEnum
    };
}